# Generated by Django 5.1.6 on 2025-04-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
