# Generated by Django 5.1.6 on 2025-05-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_attempt_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos'),
        ),
    ]
