version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    volumes:
      - .:/app
      - ../scripts:/scripts
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - dotenv_files/.env
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - dotenv_files/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d

    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
